Music-Society-Forum/Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PagedList;
using Music_Society_Forum.Models;
using Music_Society_Forum.Extensions;

namespace Music_Society_Forum.Controllers
{
    [Authorize]
    public class MyController : BaseController
    {
        // GET: My
        public ActionResult Index()
        {
            ViewBag.PostsCount = db.Posts
                        .Where(p => p.Author != null && p.Author.UserName == User.Identity.Name)
                        .Count();
            ViewBag.CommentsCount = db.Comments
                        .Include(c => c.Post)
                        .Where(c => c.Author != null && c.Author.UserName == User.Identity.Name)
                        .Count();
            return View();
        }
        
        // GET: My/Posts
        public ActionResult Posts(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var posts = db.Posts
                        .Include(p => p.Author)
                        .Include(p => p.Comments)
                        .Where(p => p.Author != null && p.Author.UserName == User.Identity.Name);

            ViewBag.IsAdmin = isAdmin();
            ViewBag.CurrentSort = sortOrder;    // keep the sort order the same while paging

            // Sorting Functionality with Column Sort Links, default -> by Date DESC
            ViewBag.TitleSortParam = sortOrder == "title_asc" ? "title_desc" : "title_asc";
            ViewBag.DateSortParam = sortOrder == "date_asc" ? "date_desc" : "date_asc";
            ViewBag.AuthorSortParam = sortOrder == "author_asc" ? "author_desc" : "author_asc";
            ViewBag.CommentsSortParam = sortOrder == "comments_asc" ? "comments_desc" : "comments_asc";

            // Paging Links
            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;
            ViewBag.CurrentFilter = searchString; // keep the search string the same & provide paging 

            // Search Functionality: in Post Title / Post Body / Author
            if (!String.IsNullOrEmpty(searchString))
            {
                posts = posts.Where(p => p.Title.Contains(searchString) ||
                                         p.Body.Contains(searchString) ||
                                         p.Author.FullName.Contains(searchString));
            }

            // Sorting 
            posts = GetSortedPosts(sortOrder, posts);
            //return View(posts.ToList());

            // Paging Links
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(posts.ToPagedList(pageNumber, pageSize));
        }

        // GET: My/Comments
        public ActionResult Comments(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var comments = db.Comments
                            .Include(c => c.Author)
                            .Include(c => c.Post)
                            .Where(c => c.Author != null && c.Author.UserName == User.Identity.Name);

            ViewBag.IsAdmin = isAdmin();
            ViewBag.CurrentSort = sortOrder;    // keep the sort order the same while paging

            // Sorting Functionality with Column Sort Links, default -> by Date DESC
            ViewBag.TitleSortParam = sortOrder == "title_asc" ? "title_desc" : "title_asc";
            ViewBag.DateSortParam = sortOrder == "date_asc" ? "date_desc" : "date_asc";
            ViewBag.AuthorSortParam = sortOrder == "author_asc" ? "author_desc" : "author_asc";

            // Paging Links
            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;
            ViewBag.CurrentFilter = searchString; // keep the search string the same & provide paging 

            // Search Functionality: in Post Title / Comment Text / Author
            if (!String.IsNullOrEmpty(searchString))
            {
                comments = comments
                    .Where(c => c.Post.Title.Contains(searchString) ||
                                c.Text.Contains(searchString) ||
                                c.Author.FullName.Contains(searchString));
            }
            // Sorting
            comments = GetSortedComments(sortOrder, comments);
            //return View(comments.ToList());

            // Paging Links
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(comments.ToPagedList(pageNumber, pageSize));
        }
                
    }
}

Music-Society-Forum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Just Music</title>
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false) @* added for datetimepicker *@
    @Scripts.Render("~/bundles/modernizr")

    @* bootstrap-datetimepicker requires jQuery to be loaded first
        => jQuery bundle moved to top of Layout page *@
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Just Music", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                                     
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Reviews", "Index", "Posts")</li>
                    <li>@Html.ActionLink("Comments", "Index", "Comments")</li>

                    @* Guest users do not see the new post view *@
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("New Review", "Create", "Posts")</li>
                        <li>@Html.ActionLink("My Texts", "Index", "My")</li>
                    }

                    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrators"))
                    {
                        <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Partial("_Notifications") @* added for notifications *@
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Software Technologies - June 2016 @@ SoftUni, Anna Stambolieva</p>
        </footer>
    </div>


    @* bootstrap-datetimepicker requires jQuery to be loaded first
        => jQuery bundle moved to top of Layout page *@
    @*@Scripts.Render("~/bundles/jquery")*@

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Music-Society-Forum/Views/Shared/_Notifications.cshtml
@using Music_Society_Forum.Extensions

@{
    var errorList = Html.GetNotifications(NotificationType.ERROR);
    var warningList = Html.GetNotifications(NotificationType.WARNING);
    var successList = Html.GetNotifications(NotificationType.SUCCESS);
    var infoList = Html.GetNotifications(NotificationType.INFO);
}
<!-- display errors -->
@if (errorList != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(errorList.Count() > 1){
            <strong><span class="glyphicon glyphicon-remove"></span> There are @errorList.Count() errors: </strong>
            <ul>
                @foreach (String message in errorList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-remove"></span> Error: </strong>
            @Html.Raw(errorList.First())
        }
    </div>
}

<!-- display warnings -->
@if (warningList != null)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(warningList.Count() > 1){
            <strong><span class="glyphicon glyphicon-warning-sign"></span> There are @warningList.Count() warnings: </strong>
            <ul>
                @foreach (String message in warningList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-warning-sign"></span> Warning: </strong>
            @Html.Raw(warningList.First())
        }
    </div>
}

<!-- display success -->
@if (successList != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(successList.Count() > 1){
            <strong><span class="glyphicon glyphicon-ok"></span> There are @successList.Count() successful notifications: </strong>
            <ul>
                @foreach (String message in successList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-ok"></span> Success! </strong>
            @Html.Raw(successList.First())
        }
    </div>
}

<!-- display success -->
@if (infoList != null)
{
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(infoList.Count() > 1){
            <strong><span class="glyphicon glyphicon-info-sign"></span> There are @infoList.Count() notifications: </strong>
            <ul>
                @foreach (String message in infoList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-info-sign"></span> </strong>
            @Html.Raw(infoList.First())
        }
    </div>
}